### ISSUE TITLE
Make Login Page

### ISSUE THREAD

**Issue by Andalv323** [Salon-App-Project/salon-app-project#8]

**Comment by ruthipy** [comment]
> No description provided.

Log in page is done for 2 users: customers and business owners.
Created button for customer to create login account.
Created button for business owner to create login account.
They can enter email, name, password, mobile number.  Submit button was created for this login page.
A placerholder was created also for profile picture and they can either use their camera or pick a picture from their phone gallery.
Users can update their profile thru the update profile button.
Users are able to logout with the logout button.
